---
title: "Number Comparison Analysis"
author: "Cassandra PW"
date: "9/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir="/Users/cpotier/BienJoue/BJAnal")
knitr::opts_chunk$set(warning=FALSE, message = FALSE)

library(readxl) ; library(readr) ; library(ggplot2) ;  library(arsenal); library(plotly) ; library(ez) ; library(ggpubr) ; library(reshape2) ;  library(plyr) ; library(tidyr) ; library(dplyr) ; library(pander); library(gmodels); require(Hmisc) ; library(afex)

panderOptions('round', 3)
panderOptions('keep.trailing.zeros', TRUE)

standarderror <- function(x) {sd(x, na.rm=T)/sqrt(sum(!is.na(x)))}
```


```{r}
symp <- read_csv("data/mergedSympTests.csv") 
SympTest <- read_csv("data/SympTest.csv") #One minute Symp Single digit
subj <- read_excel("data/subjects.xlsx")
symp$rang<-subj$subj_num[match(symp$ID, subj$test_code)] 
symp <- merge(symp, SympTest)

symp$dist <- abs(symp$left-symp$right) # get the distance 
symp$CR <- ifelse(pmax(symp$left, symp$right)==symp$button_pressed_text, 1,0) # Score

#Outcome measures
score<-aggregate(CR~rang,symp,  sum) # The number of correct button presses
time <- aggregate(rt~ rang, symp, sum) #Nobody should be over 1 min
score <- merge(score, time)
# Fix 301 and 302 have greater than possible RT...this is because the software did not stop at 1 min.

score$numbercomparisonSpeed <- (score$CR * 60000) / score$rt #Measure of speed (Correct responses * 60000) / time to complete the activity

#Measure the distance effect, on the x-axis put the distance between the compared numbers and on the y-axis the RT
time <- aggregate(rt~ rang+dist, symp[symp$CR==1, ], sum)
time$rang <- as.factor(time$rang)

ggplot(time, aes(dist, rt, color=rang)) +
  stat_summary(fun.y = 'mean', geom = "point", size = 3.5) + 
  stat_summary(fun.y = 'mean', geom = "line", aes(group = rang), linetype = "solid", size=.5) + 
  stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.1) +
  ggtitle("Distance Effect")

write.csv(time, 'data/clean/cleanDistSYMPData.csv', row.names = FALSE)
write.csv(score, 'data/clean/cleanNCRateSYMPData.csv', row.names = FALSE)
```


# One minute word and pseudoword test
```{r}
minWord <- read_csv("data/mergedMinWordTests.csv")
minWord$testName<-'minWord'
minPseudo <- read_csv("data/mergedMinPseudowordTests.csv")
minPseudo$testName<-'minPseudo'
subj <- read_excel("data/subjects.xlsx")


min<-rbind(minWord, minPseudo)
min$stimulus<-gsub("<span class=stimul>", "", min$stimulus)
min$stimulus<-gsub("</span>", "", min$stimulus)
min$rang<-subj$subj_num[match(min$ID, subj$test_code)]

x<-as.data.frame(table(min$rang, min$button_pressed_text, min$testName))
x<-spread(x, Var2, Freq)
colnames(x)[1]<-"rang"
colnames(x)[2]<-"testName"

idrt <- aggregate(rt~ rang+testName, min, sum)
x <- merge(x, idrt)

x$itemsTried<-x$Correct + x$Incorrect
x$precision <- (x$Correct / x$itemsTried) *100 #Measure of precision correct responses / total responses *100
x$readingSpeed <- (x$Correct * 60000)/x$rt #Measure of speed (Correct responses * 60000) / time to complete the activity
x

colnames(x)[5]<-'readingrt'

BJBehaviour <- merge(x, score)
write.csv(x, "data/clean/cleanMinWordPseudoData.csv", row.names = FALSE)

cor<-aggregate(readingSpeed~rang, x, mean)
cor <- merge(cor, score[,c('rang', 'numbercomparisonSpeed')])
cor

write.csv(cor, 'data/clean/cleanReadNumberData.csv', row.names = FALSE)

modellm<-lm(numbercomparisonSpeed~readingSpeed, cor)
summary(modellm)

ggplot(cor, aes(readingSpeed, numbercomparisonSpeed)) +
  geom_point() +
  geom_smooth(method='lm', alpha=0.1, fill="blue") +
  annotate("text", x = 100, y = 100, label = paste0("R Squared = ", summary(modellm)$r.squared)) +
  ggtitle("Relationship between reading and number comparison")
```


